### ISSUE TITLE
Add QR scanner

### ISSUE THREAD

**Issue by silvaDominic** [FossifyOrg/Camera#34] opened 2024-11-18 19:05 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Camera/issues) or [closed](https://github.com/FossifyOrg/Camera/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Camera/discussions) or [closed](https://github.com/FossifyOrg/Camera/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Camera/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

The camera app should incorporate a QR scan feature.

### Why do you want this feature?

Every commercial camera app features a QR scan feature. Even GrapheneOS's stock camera features one. Given how prevalent QR codes are today, this app, while intended to be simple, still feels to be missing a standard camera feature.

How this should be implemented is subject to discussion. Most commercial ones autodetect. GrapheneOS's has a dedicated camera mode. I'd personally opt for whatever is simplest to implement.

**Comment by Aga-C** [comment] 2024-11-18 19:08
It's a duplicate of https://github.com/FossifyOrg/Camera/issues/25.

**Closed by Aga-C** 2024-11-18 19:08 UTC
Labels: feature request, needs triage
